/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "bspatch.h"

JNIEXPORT jint JNICALL Java_com_patcher_PatcherUtils_patcher
  (JNIEnv *, jobject, jstring argv1, jstring argv2, jstring argv3);
